### ISSUE TITLE
Python fork libtksvg.dll bad exe format

### ISSUE THREAD

**Issue by Anonymous-Kingg** [oehhar/tksvg#19]
TclError: couldn't load library "C:/Users/Thomas King/AppData/Roaming/Python/Python37/site-packages/tksvg/libtksvg.dll": Bad exe format. Possibly a 32/64-bit mismatch.

got this error when trying to use python fork. anyone got a fix?

**Comment by oehhar** [comment]
Happy, that this is used in Pyton, propably via TkInter.
The message indicates, that probably the wrong DLL was picked from the download area.
There were confusions here caused by me proposing the wrong version (32/64 bit mismatch) but this is corrected.
You may try the libraries proposed here as releases and correct it on the Python side.
I don't know, how library loading works there.

Sorry,
Harald

**Comment by Anonymous-Kingg** [comment]
thanks

**Comment by oehhar** [comment]
Does this help:
👍 https://github.com/oehhar/tksvg/releases/tag/0.12
?
There, you have one win32 and two win64 dll's. You may try them.

**Comment by Anonymous-Kingg** [comment]
so i can use tksvg012t.dll to replace libtksvg.dll?

**Comment by oehhar** [comment]
I would just try it.
Rename the library to the original name.
If you are successful, file a bug report at tkinter.

**Comment by Anonymous-Kingg** [comment]
if i am or am not successful?

**Comment by Anonymous-Kingg** [comment]
now i get this:
_tkinter.TclError: attempt to provide package tksvg 0.7 failed: package tksvg 0.12 provided instead
do i need to get an earlier version of the dll?

**Comment by Anonymous-Kingg** [comment]
it works now thanks for the help

**Comment by oehhar** [comment]
That is good ! The DLL loads correctly !
Now to correct this:
Beside the dll, you should find a file "pckIndex.tcl".
This file should match the version. The updated pckIndex file is also provided in the release download.

**Comment by oehhar** [comment]
Happy to hear, thank you,
Harald
